# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Calendar-List
version:      0.17
version_from: lib/Calendar/List.pm
installdirs:  site
requires:
    Clone:                         0
    Test::More:                    0
    Tie::IxHash:                   0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
