--- #YAML:1.0
name:                   Calendar-List
version:                0.23
abstract:               A module for creating date lists
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  Clone:                  0
  Test::More:             0.70
  Tie::IxHash:            0
  Time::Local:            0
recommends:
  Time::Piece:            0
  Date::ICal:             0
  DateTime:               0
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0.10
build_requires:
  Test::More:             0.70

provides:
  Calendar::List:
    file:     lib/Calendar/List.pm
    version:  0.23
  Calendar::Functions:
    file:     lib/Calendar/Functions.pm
    version:  0.23
no_index:
  file:
    - t/TestData.pm
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
