--- #YAML:1.0
name:                   Calendar-List
version:                0.20
abstract:               A module for creating date lists
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Clone:                0
  Test::More:           0.47
  Tie::IxHash:          0
  Time::Local:          0
recommends:
  Time::Piece:          0
  Date::ICal:           0
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::CPAN::Meta:     0
build_requires:
  Test::More:           0.47

provides:
  Calendar::List:
    file:     lib/Calendar/List.pm
    version:  0.20
  Calendar::Functions:
    file:     lib/Calendar/Functions.pm
    version:  0.20
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
